version: "3.7"

services:
  laravel:
    image: xoren-io-laravel
    container_name: xoren-io-laravel
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./laravel/Dockerfile
      args:
        APP_ENV: ${APP_ENV:-production}
        APP_USER: ${APP_USER:-laravel}
        APP_USER_UUID: ${APP_USER_UUID:-1000}
        APP_TIMEZONE: ${APP_TIMEZONE:-Europe/London}
        APP_ENCODE: ${APP_ENCODE:-en_GB}
    working_dir: /var/www
    env_file: ./.env
    environment:
      APP_ENV: ${APP_ENV:-production}
      APP_USER: ${APP_USER:-laravel}
      SWOOLE_MAX_REQUESTS: 1000
      SWOOLE_TASK_WORKERS: 'auto'
      SWOOLE_WATCH: false
      SWOOLE_WORKERS: 'auto'
      SWOOLE_PORT: ${SWOOLE_PORT:-8000}
      XDEBUG_MODE: 'off'
      XDEBUG_CONFIG: 'client_host=host.docker.internal'
    volumes:
      - ./laravel:/var/www
      - ./php/php-ini-overrides.ini:/usr/local/etc/php/php.ini
    networks:
      - containernet
    depends_on:
      - redis
      - websocket
    ports:
      - ${SWOOLE_PORT:-8000}:${SWOOLE_PORT:-8000}

  websocket:
    image: xoren-io-websocket
    container_name: xoren-io-websocket
    restart: unless-stopped
    env_file: ./.env
    build:
      context: ./soketi
      dockerfile: Dockerfile
      args:
        APP_ENV: ${APP_ENV:-production}
        APP_TIMEZONE: ${APP_TIMEZONE:-Europe/London}
        APP_ENCODE: ${APP_ENCODE:-en_GB}
    environment:
      DEFAULT_APP_ID: app-id
      DEFAULT_APP_KEY: app-key
      DEFALT_APP_SECRET: app-secret
      SOKETI_DEBUG: '1'
      METRICS_SERVER_PORT: '9601'
      DB_REDIS_HOST: redis
      DB_REDIS_PORT: 6379
      DB_REDIS_DB: 3
      CORS_ALLOW_HEADERS: "*"
      CORS_ALLOWHEADERS: "*"
      CORS_METHODS: "*"
      CORS_ORIGIN: "*"
      CORS_CREDENTIALS: "true"
      TZ: ${APP_TIMEZONE:-Europe/London}
      TZENCODE: ${APP_ENCODE:-en_GB}
      LANG: ${APP_ENCODE:-en_GB}.UTF-8
      LANGUAGE: ${APP_ENCODE:-en_GB}.UTF-8
      LC_ALL: ${APP_ENCODE:-en_GB}.UTF-8
    networks:
        - containernet
    depends_on: 
      - redis

  nginx:
    image: xoren-io-nginx
    container_name: xoren-io-nginx
    restart: unless-stopped
    env_file: ./.env
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        APP_TIMEZONE: ${APP_TIMEZONE:-Europe/London}
        APP_ENCODE: ${APP_ENCODE:-en_GB}
    environment:
      TZ: ${APP_TIMEZONE:-Europe/London}
      TZENCODE: ${APP_ENCODE:-en_GB}
      LANG: ${APP_ENCODE:-en_GB}.UTF-8
      LANGUAGE: ${APP_ENCODE:-en_GB}.UTF-8
      LC_ALL: ${APP_ENCODE:-en_GB}.UTF-8
      SWOOLE_PORT: ${SWOOLE_PORT:-8000}
    volumes:
      - ./laravel:/var/www
    ports:
      - 80:80
      - 443:443
    networks:
      - containernet

  redis:
    image: xoren-io-redis
    container_name: xoren-io-redis
    restart: unless-stopped
    build:
      context: ./redis
      dockerfile: Dockerfile
      args:
        APP_ENV: ${APP_ENV:-production}
        APP_TIMEZONE: ${APP_TIMEZONE:-Europe/London}
        APP_ENCODE: ${APP_ENCODE:-en_GB}
    env_file: ./.env
    environment:
      TZ: ${APP_TIMEZONE:-Europe/London}
      TZENCODE: ${APP_ENCODE:-en_GB}
      LANG: ${APP_ENCODE:-en_GB}.UTF-8
      LANGUAGE: ${APP_ENCODE:-en_GB}.UTF-8
      LC_ALL: ${APP_ENCODE:-en_GB}.UTF-8
    volumes:
      - 'redisdata:/data' ## save in vm
    networks:
      - containernet
    healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        retries: 3
        timeout: 5s


networks:
  containernet:
    driver: bridge


volumes:
  redisdata:
    driver: local
  nginxconfigs:
    driver: local
  nginxconfigsopt:
    driver: local
