version: "3.7"

services:
  laravel:
    image: xoren-io-laravel
    container_name: xoren-io-laravel-local
    build:
      context: .
      dockerfile: ./laravel/Dockerfile
      args:
        APP_ENV: ${APP_ENV:-local}
        APP_USER: ${APP_USER:-laravel}
        APP_USER_UUID: ${APP_USER_UUID:-1000}
        APP_TIMEZONE: ${APP_TIMEZONE:-Europe/London}
        APP_ENCODE: ${APP_ENCODE:-en_GB}
    working_dir: /var/www
    env_file: ./.env
    environment:
      CONTAINER_ROLE: 'laravel'
      APP_ENV: ${APP_ENV:-local}
      APP_USER: ${APP_USER:-laravel}
      SWOOLE_MAX_REQUESTS:  ${SWOOLE_MAX_REQUESTS:-500}
      SWOOLE_TASK_WORKERS: ${SWOOLE_TASK_WORKERS:-auto}
      SWOOLE_WATCH: ${SWOOLE_WATCH:-false}
      SWOOLE_WORKERS: ${SWOOLE_WORKERS:-auto}
      SWOOLE_PORT: ${SWOOLE_PORT:-8000}
      XDEBUG_MODE: 'off'
      XDEBUG_CONFIG: 'client_host=host.docker.internal'
    volumes:
      - ./laravel:/var/www
      - ./php/php-ini-overrides.ini:/usr/local/etc/php/php.ini
    networks:
      - containernet
    depends_on:
      - redis
      - websocket
    ports:
      - ${SWOOLE_PORT:-8000}:${SWOOLE_PORT:-8000}

  schedule:
    image: xoren-io-schedule
    container_name: xoren-io-schedule-local
    build:
      context: .
      dockerfile: ./laravel/Dockerfile
      args:
        APP_ENV: ${APP_ENV:-local}
    working_dir: /var/www
    env_file: ./.env
    environment:
      CONTAINER_ROLE: 'schedule'
      XDEBUG_MODE: 'off'
      XDEBUG_CONFIG: 'client_host=host.docker.internal'
    volumes:
      - ./laravel:/var/www
      - ./php/php-ini-overrides.ini:/usr/local/etc/php/php.ini
    networks:
      - containernet
    depends_on:
      - laravel

  queue:
    image: xoren-io-queue
    container_name: xoren-io-queue-local
    build:
      context: .
      dockerfile: ./laravel/Dockerfile
      args:
        APP_ENV: ${APP_ENV:-local}
    working_dir: /var/www
    env_file: ./.env
    environment:
      CONTAINER_ROLE: 'queue'
      XDEBUG_MODE: 'off'
      XDEBUG_CONFIG: 'client_host=host.docker.internal'
    volumes:
      - ./laravel:/var/www
      - ./php/php-ini-overrides.ini:/usr/local/etc/php/php.ini
    networks:
      - containernet
    depends_on:
      - laravel

  queue_high:
    image: xoren-io-queue-high
    container_name: xoren-io-queue-high-local
    build:
      context: .
      dockerfile: ./laravel/Dockerfile
      args:
        APP_ENV: ${APP_ENV:-local}
    working_dir: /var/www
    env_file: ./.env
    environment:
      CONTAINER_ROLE: 'queue_high'
      XDEBUG_MODE: 'off'
      XDEBUG_CONFIG: 'client_host=host.docker.internal'
    volumes:
      - ./laravel:/var/www
      - ./php/php-ini-overrides.ini:/usr/local/etc/php/php.ini
    networks:
      - containernet
    depends_on:
      - laravel

  websocket:
    image: xoren-io-websocket
    container_name: xoren-io-websocket-local
    env_file: ./.env
    build:
      context: ./soketi
      dockerfile: Dockerfile
      args:
        APP_ENV: ${APP_ENV:-local}
        APP_TIMEZONE: ${APP_TIMEZONE:-Europe/London}
        APP_ENCODE: ${APP_ENCODE:-en_GB}
    environment:
      DEFAULT_APP_ID: app-id
      DEFAULT_APP_KEY: app-key
      DEFALT_APP_SECRET: app-secret
      DEBUG: 'true'
      SOKETI_DEBUG: '1'
      METRICS_SERVER_PORT: '9601'
      DB_REDIS_HOST: redis
      DB_REDIS_PORT: 6379
      DB_REDIS_DB: 3
      CORS_ALLOW_HEADERS: "*"
      CORS_ALLOWHEADERS: "*"
      CORS_METHODS: "*"
      CORS_ORIGIN: "*"
      CORS_CREDENTIALS: "true"
      TZ: ${APP_TIMEZONE:-Europe/London}
      TZENCODE: ${APP_ENCODE:-en_GB}
      LANG: ${APP_ENCODE:-en_GB}.UTF-8
      LANGUAGE: ${APP_ENCODE:-en_GB}.UTF-8
      LC_ALL: ${APP_ENCODE:-en_GB}.UTF-8
    ports:
      - '${SOKETI_PORT:-6001}:6001'
      - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
    networks:
      - containernet

  nginx:
    image: xoren-io-nginx
    container_name: xoren-io-nginx-local
    working_dir: /var/www
    env_file: ./.env
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        APP_TIMEZONE: ${APP_TIMEZONE:-Europe/London}
        APP_ENCODE: ${APP_ENCODE:-en_GB}
    environment:
      TZ: ${APP_TIMEZONE:-Europe/London}
      TZENCODE: ${APP_ENCODE:-en_GB}
      LANG: ${APP_ENCODE:-en_GB}.UTF-8
      LANGUAGE: ${APP_ENCODE:-en_GB}.UTF-8
      LC_ALL: ${APP_ENCODE:-en_GB}.UTF-8
      SWOOLE_PORT: ${SWOOLE_PORT:-8000}
    volumes:
      - ./laravel:/var/www
    ports:
      - 80:80
      - 443:443
    networks:
      - containernet

  mysql:
    image: xoren-io-mysql
    container_name: xoren-io-mysql-local
    env_file: ./.env
    build:
      context: ./mysql
      dockerfile: Dockerfile
      args:
        MYSQL_VERSION: ${MYSQL_VERSION:-8}
        APP_ENV: ${APP_ENV:-local}
        APP_TIMEZONE: ${APP_TIMEZONE:-Europe/London}
        APP_ENCODE: ${APP_ENCODE:-en_GB}
    cap_add:
      - SYS_NICE
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_HOST: '%'
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD:-1}
      TZ: ${APP_TIMEZONE:-Europe/London}
      TZENCODE: ${APP_ENCODE:-en_GB}
      LANG: ${APP_ENCODE:-en_GB}.UTF-8
      LANGUAGE: ${APP_ENCODE:-en_GB}.UTF-8
      LC_ALL: ${APP_ENCODE:-en_GB}.UTF-8
    volumes:
      - 'mysqldata:/var/lib/mysql'
    networks:
      - containernet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

  redis:
    image: xoren-io-redis
    container_name: xoren-io-redis-local
    build:
      context: ./redis
      dockerfile: Dockerfile
      args:
        APP_ENV: ${APP_ENV:-local}
        APP_TIMEZONE: ${APP_TIMEZONE:-Europe/London}
        APP_ENCODE: ${APP_ENCODE:-en_GB}
    env_file: ./.env
    environment:
      TZ: ${APP_TIMEZONE:-Europe/London}
      TZENCODE: ${APP_ENCODE:-en_GB}
      LANG: ${APP_ENCODE:-en_GB}.UTF-8
      LANGUAGE: ${APP_ENCODE:-en_GB}.UTF-8
      LC_ALL: ${APP_ENCODE:-en_GB}.UTF-8
    volumes:
      - 'redisdata:/data'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    networks:
      - containernet
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s

networks:
  containernet:
    driver: bridge

volumes:
  mysqldata:
    driver: local
  redisdata:
    driver: local
